id: I70048B45
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:15:57+00:00'
last_modified: '2022-06-08T02:40:05.239051+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28973
  title: བོད་མིའི་ཚེ་སྲོག་གླེང་བའི་ལྷག་བསམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FBBB:
      image_group_id: I1KG12364
      title: ''
      total_pages: 416
      order: 1
      base_file: FBBB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
