id: P005379
initial_creation_type: ocr
source_metadata:
  id: bdr:W28973
  title: བོད་མིའི་ཚེ་སྲོག་གླེང་བའི་ལྷག་བསམ།
  author: ''
  volumes:
    7493923410e24be69af2f5abd00bc738:
      image_group_id: I1KG12364
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
